name: Docker Image CI

on: [push]

jobs:

  build:
    name: Build & Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: ./docker-build.sh "${GITHUB_REF#refs/heads/}"
    - name: Run tests
      run: docker run --rm -e PROCESS_TYPE=test --name django-coleman "mrsarm/django-coleman:${GITHUB_REF#refs/heads/}"
